### ISSUE TITLE
Enumerate

### ISSUE THREAD

**Issue by jasperdenduijf** [sliemelela/antiproteine#2]
Op een aantal plekken, zoals visualise.py, gebruiken jullie nog zelfgemaakte counters in je for-loop. Je kunt hiervoor ook de functie `enumerate()` gebruiken, dat wordt gezien als mooiere Python code. Google hoe je dit in een for-loop kunt gebruiken.

**Comment by sliemelela** [comment]
Ik heb dit verwerkt! Dank voor de tip!
